---
title: "My-Github-Live-pages"
theme: minima
author: vamsi Devarapalli
email: vamsi63042@bmail.com
description: > hi .. my name is vamsi and i am from ap and i joined in apollo as software developer in it product development team..."
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: vamsi-Devarapalli # DO NOT include the @ character, or else the build will fail!
github_username:  vamsi7997# DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
---
